on:
  push:
    branches:
      - main

name: Render and Publish Quarto Site

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Render Quarto project
        run: |
          quarto render

      - name: Copy static assets to public folder
        run: |
          cp -R images/* public/images/

      - name: Upload HTML files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: quarto-html-output
          path: public/**/*.html

      - name: Commit and push specific files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add public/index.html
          git add public/simulation.html
          git add public/ASReviewLAB.html
          git add public/datatools.html

          git add public/images/
          
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update Quarto files"
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}