on:
  push:
    branches:
      - main

name: Render and Publish Quarto Site

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Render Quarto project
        run: |
          quarto render

      - name: Upload HTML files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: quarto-html-output
          path: docs/**/*.html
